engine:
  type: redis
  redis:
    address: redis:6379

log:
  level: debug

client:
  token:
    hmac_secret_key: 84f0ecda97c5eebd8f1c0de8f468703660f0fb165c54d01d7fc672d2baa2adc6
  allowed_origins:
    - http://127.0.0.1:3000
    - http://localhost:3000

channel:
  without_namespace:
    allow_subscribe_for_client: false
  namespaces:
    - name: personal_events
      allow_subscribe_for_client: true
      allow_user_limited_channels: true

admin:
  enabled: true
  password: password
  secret: 4e9eafcf-0120-4ddd-b668-8dc40072c78e
